# Generated by Django 4.1.3 on 2022-11-20 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room_app', '0002_demo_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
