# Generated by Django 4.1.3 on 2022-11-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_app', '0003_demo_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Room_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Room_Type', models.CharField(choices=[('Single Room', 'Single Room'), ('Full Room', 'Full Room'), ('Sharing Room', 'Sharing Room')], default='1', max_length=20)),
                ('Proof', models.ImageField(upload_to='proofs/')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('Name', models.CharField(max_length=100)),
                ('Name_2', models.CharField(blank=True, max_length=100)),
                ('Address', models.TextField(blank=True)),
                ('Designation', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('Emergency_number', models.CharField(blank=True, max_length=12)),
                ('vehicel_number', models.CharField(blank=True, max_length=12)),
                ('Advance', models.CharField(blank=True, max_length=10)),
                ('Check_in_date', models.DateTimeField(blank=True)),
                ('Check_out_date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
