# Generated by Django 4.1.3 on 2022-11-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_app', '0005_alter_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Room_No',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
