# Generated by Django 4.1.3 on 2022-12-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_app', '0006_alter_booking_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Proof',
            field=models.ImageField(upload_to='proofs'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='photo',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
